# Generated by Django 4.2.7 on 2023-12-02 14:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("calculator", "0002_rename_currency_pln_currencypln"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CurrencyPln",
            new_name="CurrencyEur",
        ),
    ]
