# Generated by Django 4.2.7 on 2023-12-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calculator", "0003_rename_currencypln_currencyeur"),
    ]

    operations = [
        migrations.CreateModel(
            name="CurrencyUSD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("effective_date", models.DateTimeField(verbose_name="Effective date")),
                (
                    "bid",
                    models.FloatField(verbose_name="converted currency purchase rate"),
                ),
                (
                    "ask",
                    models.FloatField(verbose_name="converted currency selling rate"),
                ),
                (
                    "mid",
                    models.FloatField(verbose_name="converted average currency rate"),
                ),
            ],
        ),
    ]
