# Generated by Django 4.2.7 on 2023-12-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calculator", "0004_currencyusd"),
    ]

    operations = [
        migrations.CreateModel(
            name="CurrencyRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("effective_date", models.DateTimeField(verbose_name="Effective date")),
                (
                    "mid",
                    models.FloatField(verbose_name="converted average currency rate"),
                ),
                ("code", models.CharField(verbose_name="Code of currency")),
                ("currency", models.CharField(verbose_name="description")),
            ],
        ),
        migrations.DeleteModel(
            name="CurrencyEur",
        ),
        migrations.DeleteModel(
            name="CurrencyUSD",
        ),
    ]
