# Generated by Django 4.2.7 on 2023-12-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calculator", "0005_currencyrate_delete_currencyeur_delete_currencyusd"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currencyrate",
            name="effective_date",
            field=models.DateField(verbose_name="Effective date"),
        ),
    ]
